hackernews/urls.py
from django.urls import path, include
from . import views

urlpatterns=[
	path('login', views.index, name='login'),
	path('create_account', views.create_account, name='create_account'),
	path('home', views.home, name='home'),
	path('comments/<int:newslink_id>', views.comments, name='comments'),
	path('logout', views.logout_func, name='logout'),
	path('reply/<int:comment_id>', views.reply, name='reply'),
	path('search', views.search, name='search'),
	path('submit', views.submit, name='submit'),

	#Ajax Vote Newslink 
	path('vote_newslink', views.vote_newslink, name='vote_newslink'),
	#Ajax Vote Comment
	path('vote_comment', views.vote_comment, name='vote_comment'),
]

hackpy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hackernews/', include('hackernews.urls')),
]

hackernews/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

import django.db.models.options as options
import django.db.models.options as options
options.DEFAULT_NAMES = options.DEFAULT_NAMES + (
	'es_index_name', 'es_type_name', 'es_mapping'
)

# Create your models here.


class ProfileUser(AbstractUser):
	username = models.CharField(max_length=100, unique=True)

	# REQUIRED_FIELDS = ['username']

	def __str__(self):
		return self.username

class NewsLinks(models.Model):
	title = models.CharField(max_length=300, null=True, blank=True)
	posted_by = models.ForeignKey(ProfileUser, on_delete=models.CASCADE, null=True, blank=True)
	title_link = models.URLField(max_length=400, null=True, blank=True)
	base_url = models.URLField(max_length=100, null=True, blank=True)
	num_comments = models.PositiveIntegerField(default=0, null=True, blank=True)
	hackernews_post_id = models.PositiveIntegerField(unique=True, null=True, blank=True)
	# karma_points = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
	karma_points = models.CharField(max_length=15, null=True, blank=True)
	time_posted = models.DateTimeField(null=True, blank=True)

	upvotes = models.PositiveSmallIntegerField(default=0, null=True, blank=True)
	downvotes = models.PositiveSmallIntegerField(default=0, null=True, blank=True)

	def __str__(self):
		return '%s - %s' % (self.id, self.hackernews_post_id)

	'''
	def indexing(self):
		obj = NewsLinksIndex(meta={'id': self.id}, title=self.title)
		return obj.to_dict()
	'''
	class Meta:
		es_index_name = 'django'
		es_type_name = 'newslink'
		es_mapping = {
				'properties': {
					'newslinkindex': {
						'type': 'object',
						'properties': {
							'title': {'type': 'string', 'index': 'not_analyzed'},
						}
					},
					
				}
			}

	def es_repr(self):
		data = {}
		mapping = self._meta.es_mapping
		data['_id'] = self.pk
		'''
		for field_name in mapping['properties'].keys():
			data[field_name] = self.field_es_repr(field_name)
		'''
		data['title'] = self.title	
		return data
	'''
	def field_es_repr(self, field_name):
		config = self._meta.es_mapping['properties'][field_name]
		if hasattr(self, 'get_es_%s' % field_name):
			field_es_value = getattr(self, 'get_es_%s' % field_name)()
		else:
			if config['type'] == 'object':
				related_object = getattr(self, field_name)
				field_es_value = {}
				field_es_value['_id'] = related_object.pk
				for prop in config['properties'].keys():
					field_es_value[prop] = getattr(related_object, prop)
			else:
				field_es_value = getattr(self, field_name)
		return field_es_value
	'''


class Comments(models.Model):
	newslink = models.ForeignKey(NewsLinks, on_delete=models.CASCADE)
	content = models.CharField(max_length=10000)
	posted_by = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)        
	added_on = models.DateTimeField(auto_now_add=True)
	comment = models.ForeignKey('Comments', null=True, blank=True, on_delete=models.CASCADE)
	hnnews_id = models.PositiveIntegerField(blank=True, null=True)
	upvotes = models.PositiveSmallIntegerField(default=0, null=True, blank=True)

	def __str__(self):
		return '%s' % (self.id)

class UpvotesNewslink(models.Model):
	newslink_voted = models.BooleanField(default=False)
	voted_by = models.ForeignKey(ProfileUser,on_delete=models.CASCADE)
	newslink = models.ForeignKey(NewsLinks, on_delete=models.CASCADE)

class UpvotesComment(models.Model):
	comment_voted = models.BooleanField(default=False)
	voted_by = models.ForeignKey(ProfileUser, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comments, on_delete=models.CASCADE) 

hackernews/forms.py
from django import forms

from .models import Comments, ProfileUser, NewsLinks

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comments
		fields = ['content']

class RegisterUser(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = ProfileUser
		fields = ('username', 'password')

class AddLink(forms.ModelForm):

	class Meta:
		model = NewsLinks
		fields = ('title','title_link')

hackernews/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import get_object_or_404

import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
import datetime
from elasticsearch import Elasticsearch
import json


# from .tasks import test, return_5, myfunc
from .tasks import myfunc, add_to_index
from .models import NewsLinks, ProfileUser, Comments, UpvotesNewslink, UpvotesComment
from .forms import CommentForm, RegisterUser, AddLink
from hackernews.management.commands.push_to_index import Command


client = settings.ES_CLIENT


# Create your views here.

def index(request): 
	myfunc.delay()
	form = RegisterUser()
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home')

	return render(request, 'hackernews/login.jinja' ,{'form':form})

def comments(request, newslink_id):
	form = CommentForm()
	comments = Comments.objects.filter(newslink=newslink_id)
	newslink = NewsLinks.objects.filter(id=newslink_id).last()
	user_posted_by = ProfileUser.objects.filter(username=request.user.username).last()

	comment_votes = UpvotesComment

	if request.method=='POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			form_save = form.save(commit=False)
			form_save.newslink = newslink
			form_save.posted_by = user_posted_by
			form_save.save()
			return redirect('comments', newslink_id=newslink.id)
		else:
			print(form.errors)

	ctx = {
			'comments': comments,
			'newslink': newslink,
			'form': form,
			'comment_votes': comment_votes
	}
	
	return render(request, 'hackernews/comments.jinja', ctx)

def search(request):
	# text = request.GET.get('q')
	
	'''
	filtered_links = NewsLinks.objects.filter(title__icontains=text)
	ctx = {
		'filtered_links':filtered_links,
	}
	'''

	query = request.GET.get('q')
	es = Elasticsearch()
	# resp = es.search(index="django", body={"size":100, "query": {"bool": {"should": [{"multi_match": {"query": query,"fields": ["title^5","title.ngram"]} }] } } })
	resp = es.search(index="django", body={"size":100, "query": {
    "multi_match": {
      "fields":  [ "title" ],
      "query": query,
      "fuzziness": "AUTO"
    }
  } })

	res = resp['hits']['hits']
	linklist = []
	for r in res:
		l_id = int(r['_id'])
		# link = get(NewsLinks, pk=l_id)
		link = NewsLinks.objects.filter(id=l_id).last()
		linklist.append(link)

	ctx = {
		'filtered_links':linklist,
	}
	return render(request,'hackernews/search.jinja',ctx)

def create_account(request):
	form = RegisterUser(request.POST)
	if request.method == 'POST':
		if form.is_valid():
			form_save = form.save(commit=False)
			form_save.set_password(request.POST.get('password'))
			form_save.save()
			
			return HttpResponseRedirect(reverse('index'))
			

		return render(request, 'hackernews/home.jinja', {'form':form})
	return render(request, 'hackernews/login.jinja', {'form':form})

def logout_func(request):
	logout(request)
	return HttpResponseRedirect(reverse('login'))

def vote_newslink(request):
	newslink_id = request.GET.get('newslink_id')
	newslink = NewsLinks.objects.get(id=newslink_id)
	user = request.GET.get('username')
	user = ProfileUser.objects.filter(username=user).last()
	vote_newslink,_ = UpvotesNewslink.objects.get_or_create(newslink_voted=True, voted_by=user, newslink=newslink)

	newslink.upvotes += 1
	newslink.save()

	return HttpResponse('SUCCESS')

def vote_comment(request):
	comment_id = request.GET.get('comment_id')
	comment = Comments.objects.get(id=comment_id)
	user = request.GET.get('username')
	user = ProfileUser.objects.filter(username=user).last()
	vote_comment,_ = UpvotesComment.objects.get_or_create(comment_voted=True, voted_by=user, comment=comment)

	comment.upvotes += 1
	comment.save()

	return HttpResponse('SUCCESS')  

def reply(request,comment_id):
	comment = Comments.objects.filter(id=comment_id).last()
	user_posted_by = ProfileUser.objects.filter(username=request.user.username).last()
	form = CommentForm()

	if request.method=='POST':
		form=CommentForm(request.POST)
		if form.is_valid():
			form_save = form.save(commit=False)
			form_save.newslink = comment.newslink
			form_save.posted_by = user_posted_by
			form_save.comment = comment
			form_save.save()
			return redirect('comments', newslink_id=comment.newslink.id)
		else:
			print(form.errors)

	ctx = {
		'comment':comment,
		'form': form
	}
	
	return render(request, 'hackernews/reply.jinja', ctx)

def submit(request):
	ctx={}
	form = AddLink()
	if request.method == 'POST':
		form = AddLink(request.POST)
		if form.is_valid():
			form_save = form.save(commit=False)
			form_save.posted_by = request.user
			form_save.base_url = urlparse(form_save.title_link).netloc
			form_save.time_posted = datetime.datetime.now()
			form_save.save()
			add_to_index.delay()
			return redirect('home')

	add_to_index.delay()

	return render(request,'hackernews/submit.jinja',ctx)

@login_required(login_url='login')
def home(request):
	ctx = {}
	newslinks = NewsLinks.objects.all()
	# print(newslinks[0].time_posted)
	paginator = Paginator(newslinks, 30)    
	page = request.GET.get('page')
	newslinks = paginator.get_page(page)

	newslink_votes = UpvotesNewslink

	ctx = {
	'newslinks': newslinks,
	'newslink_votes': newslink_votes,
	}
	
	return render(request, 'hackernews/home.jinja', ctx)

hackernews/templates/hackernews/comments.jinja
<html op="item"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?7orY7hm2Oh1MPMHDSbS8">
            <link rel="shortcut icon" href="favicon.ico">
            <script src="/static/js/moment.js"></script>
        <title>{{ newslink.title }} | Hacker News</title></head>

        <body>
          <center>
    <table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
   <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="{{ url('home') }}"><img src="/static/images/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
   <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="{{ url('home') }}">Hacker News</a></b>
   <a href="#">new</a> | <a href="#">threads</a> | <a href="#">past</a> | <a href="#">comments</a> | <a href="#">ask</a> | <a href="#">show</a> | <a href="#">jobs</a> | <a href="{{ url('submit') }}">submit</a></span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
     {{ request.user.username }} | <a href="{{ url('logout') }}">logout</a>
    </span></td></tr></table></td></tr>

    <tr id="pagespace" title="{{ newslink.title }}" style="height:10px"></tr><tr><td><table class="fatitem" border="0">

      <table class="fatitem" border="0">
      <tbody><tr class="athing">
      <td align="right" valign="top" class="title"><span class="rank"></span></td><td valign="top" class="votelinks"></td><td class="title"><a href="{{ newslink.title_link }}" class="storylink">{{ newslink.title }}</a><span class="sitebit comhead"> (<a href=""><span class="sitestr">enclydion.blogspot.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_19644206">{{newslink.karma_points}}</span> by {{ newslink.posted_by }} <span class="age">posted on <a href="{{ url('comments', newslink_id=newslink.id) }}"><script> document.write(moment("{{newslink.time_posted.strftime("%Y%m%d")}}", "YYYYMMDD").fromNow()); </script></a></span> <span id="unv_19644206"></span> | <a href="{{ url('comments', newslink_id=newslink.id) }}">{{ newslink.num_comments }}&nbsp;comments</a>              </td></tr>
            <tr style="height:10px"></tr><tr><td colspan="2"></td><td>
          <form method="POST" action="{{ url('comments', newslink_id=newslink.id) }}">
            {% csrf_token %}
            <label>Add Comment</label>
             <div class="form-group">
                            <textarea rows="9" cols="60" name="content" class="form-control">{% if form.content.value() %}{{ form.content.value() }}{% else %}{% endif %}</textarea>
                          </div>
            <br><br><input type="submit" value="add comment"></form>
      </td></tr>
  </tbody></table>

{% for comment in comments recursive %}
<table border="0"><tbody><tr>    
  <li style="list-style: none;">
    <td class="ind">
      <img height="1" width="0">
    </td>
    <td valign="top" class="votelinks"></td>
    {% if comment_votes.objects.filter(voted_by=request.user, comment=comment).exists() %}
      &nbsp &nbsp
    {% else %}
      <a id="{{ comment.id }}" class="vote" href="">&nbsp &#x25B2 </a>
    {% endif %}
    </td><span class="comhead">{{ comment.posted_by }} <span class="age">| posted: <a href="item?id=19645124"><script> document.write(moment("{{ comment.added_on.strftime("%Y%m%d") }}", "YYYYMMDD").fromNow()); </script></a></span> <span id="unv_19645124"></span><span class="par"></span>          <span class="storyon"></span></span></div><br>
        <div class="comment">
                    <span class="commtext c00"><code>{{ comment.content }}</code></span>
                    <div class='reply'>        <p><font size="1">
                        <u><a href="{{url('reply',comment_id=comment.id)}}">reply</a></u>
                    </font></p><br>
        </div>
      </div>
    </td>
  </tr></tbody></table>

  {% if comment.comments_set.all() %}
      <ul style="list-style: none;">{{ loop(comment.comments_set.all()) }}</ul>      
  {% endif %}
  </li>
{% endfor %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
$('.vote').on('click', function(e) {
    var comment_id = $(this).attr("id");
    $.ajax({
        url: "{{ url('vote_comment') }}",
        type: 'GET',
        data: {
          'comment_id': comment_id,
          'username': '{{ request.user.username }}',
        },
        success: function (res) {
          $('#'+comment_id).css("visibility", "hidden");
          console.log('upvoted');
        },
        error: function (jqXHR) {
            console.log('unable to vote');
        }
    })
});

</script>

{# {% for c in comments recursive %}
    <li>
        {{ c.content }}
        {% if c.comments_set.all() %}
            <ul>{{ loop(c.comments_set.all()) }}</ul>

        {% endif %}
    </li>
{% endfor  %} #}

hackernews/templates/hackernews/home.jinja
<!DOCTYPE html>
<html>
<head>
	<title>Hacker News Clone Home</title>
	<style type="text/css"></style>
	<link rel="stylesheet" href="{{ static('css/hackernews/hackernews.css') }}">
  <script src="/static/js/moment.js"></script>
</head>
<body>

<center>
	<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tbody>
			<tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
		<tbody>
		<tr><td style="width:18px;padding-right:4px"><a href="{{ url('home') }}"><img src="/static/images/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="{{ url('home') }}">Hacker News</a></b>
              <a href="#">new</a> | <a href="#">past</a> | <a href="#">comments</a> | <a href="#">ask</a> | <a href="#">show</a> | <a href="#">jobs</a> | <a href="{{ url('submit') }}">submit</a></span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                            {{ request.user.username }}  | <a href="{{ url('logout') }}">logout</a>
                          </span></td>
        </tr></tbody></table></td></tr>

    <tr id="pagespace" title="" style="height:10px"></tr>

    <tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">

    <tbody>

	{% for newslink in newslinks[::-1] %}
      <tr class="athing" id="">
      <td align="right" valign="top" class="title">
      	<span class="rank">
      	{{ (30*(newslinks.number-1))+loop.index }} 
      	</span>
      </td>
      <td valign="top" class="votelinks">
      	<center>
      		{% if newslink_votes.objects.filter(voted_by=request.user, newslink=newslink).exists() %}
      			&nbsp &nbsp
      		{% else %}
      			<a id="{{ newslink.id }}" class="vote" href="#">&nbsp &#x25B2 </a>
      		{% endif %}
      	</center>
      </td>
      <td class="title">
      	<a href="{{ newslink.title_link }}" class="storylink">{{ newslink.title }}</a>
      	<span class="sitebit comhead"> (<a href=""><span class="sitestr">{{ newslink.base_url }}</span></a>)</span>
      	<tr><td colspan="2"></td>
      		<td class="subtext">
        	<span class="score" id="score_19580860">{{ newslink.karma_points }}</span> by <a href="#" class="hnuser">{{ newslink.posted_by }}</a> <span class="age">{% if newslink.time_posted %}<a href="{{ url('comments', newslink_id=newslink.id) }}"><script> document.write(moment("{{newslink.time_posted.strftime("%Y%m%d")}}", "YYYYMMDD").fromNow()); </script></a>{% endif %}</span> | <a href="{{ url('comments', newslink_id=newslink.id) }}">{{ newslink.num_comments }}&nbsp;comments</a>              
        	</td>
        </tr>
      <tr class="spacer" style="height:5px"></tr>
    {% endfor %}
		
  	</tbody>

</table>

<div class="pagination">
		    <span class="step-links">
		        {# {% if newslinks.has_previous() %}
		            <a href="?page={{ newslinks.previous_page_number() }}"> << </a>
		        {% endif %} #}

		        {# <span class="current">
		            Page {{ newslinks.number }} of {{ newslinks.paginator.num_pages }} 
		        </span> #}

		        {% if newslinks.has_next() %}
		            &nbsp &nbsp <a href="?page={{ newslinks.next_page_number() }}"> more </a>
		        {% endif %}
		    </span>
		</div>
</td></tr>

</tbody>

<td><img height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tbody><tr><td bgcolor="#ff6600"></td></tr></tbody></table><br><center><span class="yclinks"><a href="#">Guidelines</a>
        | <a href="#">FAQ</a>
        | <a href="#">Support</a>
        | <a href="#">API</a>
        | <a href="#">Security</a>
        | <a href="#">Lists</a>
        | <a href="#" rel="nofollow">Bookmarklet</a>
        | <a href="#">Legal</a>
        | <a href="#">Apply to YC</a>
        | <a href="#">Contact</a></span><br><br>
        <form method="GET" action="{{ url('search') }}">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"><input type="submit" value="Search"></form><br>
            </center></td>

        </table>
 


</center>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script type="text/javascript">
$('.vote').on('click', function(e) {
    var newslink_id = $(this).attr("id");
    $.ajax({
        url: "{{ url('vote_newslink') }}",
        type: 'GET',
        data: {
        	'newslink_id': newslink_id,
        	'username': '{{ request.user.username }}',
        },
        success: function (res) {
        	$('#'+newslink_id).css("visibility", "hidden");
        	console.log('upvoted');
        },
        error: function (jqXHR) {
            console.log('unable to vote');
        }
    })
});

</script>

hackernews/templates/hackernews/login.jinja
<html>
<head>
	<title>Login - HackerNews Clone</title>
</head>
<body>
    <b>Login</b><br><br>
<form method="post" action="{{ url('login') }}">
	{% csrf_token %}
	<table border="0">
		<tr>
			<td>username:</td><td><input type="text" name="username" size="20" autocorrect="off" spellcheck="false" autocapitalize="off" autofocus="true"></td>
		</tr>
		<tr>
			<td>password:</td><td><input type="password" name="password" size="20"></td>
		</tr>
	</table><br>

<input type="submit" value="login"></form>
<!--
<b>Create Account</b><br><br>
<form method="post" action="{{ url('create_account') }}">
	{% csrf_token %}
	<table border="0">
		<tr>
			<td>username:</td><td><input type="text" name="username" size="20" autocorrect="off" spellcheck="false" autocapitalize="off"></td>
		</tr>
		<tr>
			<td>password:</td><td><input type="password" name="password" size="20"></td>
		</tr>
	</table><br>

<input type="submit" value="create account"></form>
-->
</body>
</html>

hackernews/templates/hackernews/reply.jinja
<html op="reply"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?bOpWWKekf2Awoctu6Y0y">
            <link rel="shortcut icon" href="favicon.ico">
            <script src="/static/js/moment.js"></script>
        <title>Add Comment | Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="{{ url('home') }}"><img src="/static/images/y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b>Add Comment</b></span></td>
              <td style="text-align:right;padding-right:4px;"><span class="pagetop">
                          <b><a href="{{ url('home') }}">Home</a></b> | <a href="{{ url('logout') }}">logout</a>
                          </span></td></tr></table></td></tr>
<tr id="pagespace" title="Add Comment" style="height:10px"></tr><tr><td><table class="fatitem" border="0">
    <tr class='athing' id='19659584'>    <td class='ind'></td><td valign="top" class="votelinks"><center><a id='up_19659584' onclick='return vote(event, this, "up")' href='vote?id=19659584&amp;how=up&amp;auth=cfa6190a86be16c38919fc198677cae909ba2bd2&amp;goto=reply%3Fgoto%3Ditem%253Fid%253D19658503%252319659584%26id%3D19659584#19659584'><div class='votearrow' title='upvote'></div></a></center></td><td class="default"><div style="margin-top:2px; margin-bottom:-10px;"><span class="comhead">
          <a href="user?id=cliffreich" class="hnuser">{{comment.posted_by}}</a> <span class="age">| posted on: <a href="item?id=19659584"><script> document.write(moment("{{comment.added_on.strftime("%Y%m%d")}}", "YYYYMMDD").fromNow()); </script></a></span> <span id="unv_19659584"></span><span class="par"> </span> <a class="togg" n="2" href="javascript:void(0)" onclick="return toggle(event, 19659584)"></a> <span class='storyon'> | on: {{comment.newslink.title}}</span>
                  </span></div><br><div class="comment">
                  <span class="commtext c00">{{comment.content| safe}}</span>
              <div class='reply'></div></div></td></tr>
  <tr style="height:10px"></tr><tr><td colspan="2"></td><td>
          <form method="POST" action="{{ url('reply', comment_id=comment.id) }}">
            {% csrf_token %}
            <label>Add Comment</label>
             <div class="form-group">
              <textarea rows="9" cols="60" name="content" class="form-control">{% if form.content.value() %}{{ form.content.value() }}{% else %}{% endif %}</textarea>
            </div>
            <br><br><input type="submit" value="add comment"></form>
      </td></tr>
</table></td></tr>
      </table></center></body><script type='text/javascript' src='hn.js?bOpWWKekf2Awoctu6Y0y'></script>
  </html>

hackernews/templates/hackernews/submit.jinja
<html op="submit">
<head>
	<meta name="referrer" content="origin">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="news.css?kq1kzKjRe95dmqHo68Cz">
	<link rel="shortcut icon" href="favicon.ico">
	<title>Submit | Hacker News</title>
</head>

<body>
	<center>
		<table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
			<tr>
				<td bgcolor="#ff6600">
					<table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px">
						<tr>
							<td style="width:18px;padding-right:4px">
								<a href="https://news.ycombinator.com">
									<img src="/static/images/y18.gif" width="18" height="18" style="border:1px #ffffff solid;">
								</a>
							</td>
							<td style="line-height:12pt; height:10px;">
								<span class="pagetop"><b>Submit</b>
								</span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr style="height:10px"></tr>
			<tr>
				<td>
					<form method="POST" action="{{ url('submit') }}">
						{% csrf_token %}
						<table border="0">
							<tr>
								<td>title</td>
								<td>
									<input type="text" name="title" value="" size="50"><span style="margin-left:10px"></span>
								</td>
							</tr>
							<tr style="height:10px">
								<td></td>
								<td></td>
							</tr>
							<tr>
								<td>url</td>
								<td><input type="text" name="title_link" value="" size="50"></td>
							</tr>
							<tr>
								<td></td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td><input type="submit" value="submit"></td>
							</tr>
							<tr style="height:20px"></tr>
							<tr>
								<td></td>
								<td>Leave url blank to submit a question for discussion. If there
							         is no url, the text (if any) will appear at the top of the
							         thread.<br><br>
							    </td>
							</tr>
						</table>
					</form>
				</td>
			</tr>
		</table>
	</center>
</body>

</html>